name: deploy

on:
  workflow_run:
    workflows: ["build/test"]
    branches: [master]
    types:
      - completed


jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master

      - name: Restore cached yarn build
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}-

      - name: Copy file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
          AWS_S3BUCKET_NAME: ${{ secrets.AWS_S3BUCKET_NAME }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_NAME }}
        run: |
          aws s3 sync dist/ s3://$AWS_S3BUCKET_NAME --delete

      - name: Invalidate CloudFront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
          CF_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION --paths '/*';
